apiVersion: v1
kind: Secret
metadata:
  name: jenkins-creds
  namespace: jenkins
data:
  options: LS1hcmd1bWVudHNSZWFsbS5wYXNzd2QuamVua2lucz1DSEFOR0VfTUUgLS1hcmd1bWVudHNSZWFsbS5yb2xlcy5qZW5raW5zPWFkbWluCg==
  
