kind: PersistentVolume
apiVersion: v1
metadata:
  name: jenkins-home
  namespace: jenkins
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Users/nikolaybiryukov/kube_volumes/jenkins"
    type: DirectoryOrCreate